#!/bin/sh

# Execute as
# ./create_dot | dot -Tpng -o/var/www/html/dibu.png

echo "digraph md253 {"
echo

echo "compound=true;"
echo

FUNCTIONS=$( sed -n -e 's/^\(.*\)() \?{/\1/p' bootfs/etc/sysconfig/libexec/modules/*/* )

CGIS=$( ls bootfs/var/www/cgi-bin/* )

for f in ${FUNCTIONS} ; do
  FOUND=NO
  for source in $( grep -rwl $f bootfs/etc/sysconfig/libexec/modules/*/* 2> /dev/null ) ; do
    if [ $f != ${source##*/} ] ; then
      echo "\"${source##*/}\" -> \"$f\";"
    else
      FOUND=YES
      fi
    done
  if [ $FOUND = YES ] ; then
    if [ ${f#service_} = $f ] ; then
      echo "\"$f\";"
    else
      echo "\"$f\" [ label=\"${f#service_}\" ];"
      fi
  else
    echo "\"$f\" [ peripheries=2 ];"
    fi
  done

echo

for f in ${CGIS} ; do
  echo "\"${f}\" [ label=\"${f##*/}\" , shape=rectangle , peripheries=2 ];"
  done

for f in ${FUNCTIONS} ${CGIS} ; do
  grep -rwl ${f##bootfs/var/www/} bootfs rootfs 2> /dev/null
  done | egrep -v 'bootfs/etc/sysconfig/(libexec/modules|system-script)/' | \
    sort -u | while read source ; do
      echo "\"${source}\" [ label=\"${source##*/}\" , shape=rectangle ];"
      done

echo

cat <<EOF
"bootfs/etc/init.d/rc.sysinit" -> "bootfs/etc/init.d/rc.sysmount";
"bootfs/etc/init.d/rc.sysinit" -> "bootfs/etc/init.d/rc.services";
"bootfs/etc/init.d/rc.sysinit" -> "rootfs/bin/buttons_daemon";
EOF

echo

for f in ${FUNCTIONS} ${CGIS} ; do
  for source in $( grep -rwl ${f##bootfs/var/www/} bootfs rootfs 2> /dev/null | grep -v bootfs/etc/sysconfig/libexec/modules/ ) ; do
      echo "\"$source\" -> \"$f\";"
    done
  done

echo

SCRIPTS=$( ls bootfs/etc/sysconfig/system-script/* )
for script in ${SCRIPTS} ; do
  echo "\"${script}\" [ label=\"${script##*/}\" , shape=rectangle , peripheries=2 ];"
  done

cat <<EOF
"bootfs/etc/udev/rules.d/10-local.rules" [ label="udev.rules" ];
"bootfs/etc/sysconfig/config/root" [ label="crontab" ];
"rootfs/bin/buttons_daemon" [ label="buttons_daemon" , shape=rectangle ];
EOF

echo

for f in ${SCRIPTS} ; do
  for source in $( grep -rwl ${f#bootfs} bootfs rootfs 2> /dev/null | grep -v rootfs/sbin/buttons_daemon ) ; do
      if [ $f != ${source##*/} ] ; then
        echo "\"${source#bootfs/etc/sysconfig/libexec/modules/*/}\" -> \"$f\";"
        fi
    done
  done

echo

cat <<EOF
"service_start" -> "service_ftp_start" [ style=dashed , lhead=cluster_svcstart ];
"service_stop" -> "service_ftp_stop" [ style=dashed , lhead=cluster_svcstop ];
EOF

cat <<EOF
subgraph cluster_svcstart {
"service_btpd_start";
"service_ftp_start";
"service_smb_start";
"service_daapd_start";
}

subgraph cluster_svcstop {
"service_btpd_stop";
"service_ftp_stop";
"service_smb_stop";
"service_daapd_stop";
}
EOF

echo
echo "}"

