#!/bin/sh

if [ $# -ne 1 ] ; then
  echo "Usage : do_boot_image version"
  exit 1
  fi

FW="SitecomNas.$1"

add_file() {
  md5sum $2.bin > $2.bin.md5sum
  tar -uf $1 --remove-files $2.bin $2.bin.md5sum
  }


# Remove previous firmware
rm -f $FW.bin

set -e


# Create boot filesytem image

dd if=/dev/zero of=initrd.img bs=1M count=3
mke2fs -F -b 1024 -i 1024 initrd.img
tune2fs -c 0 -i 0 initrd.img

mkdir image
mount -o loop -t auto initrd.img image
tar cC bootfs . | tar xC image

tar xC image -f devices.tar

cd image
mkdir -p home mnt proc root sys tmp
mkdir -p usr/local usr/share/system var/spool/system
mkdir -p etc/sysconfig/config/smb/folders etc/sysconfig/config/smb/private etc/sysconfig/config/smb/shares
cd ..

echo 'ttyS0::respawn:/sbin/getty -L ttyS0 115200 vt100' >> image/etc/inittab
echo "SitecomNas_v$1" > image/etc/sysconfig/config/version

umount image
rmdir image

# Flash is capable of at least 589286 bytes from 2.4.15
cat initrd.img | gzip -9 > bootfs.bin
DEV=$( losetup -j initrd.img )
losetup -d ${DEV%%:*}
rm -f initrd.img

add_file $FW.bin bootfs



# Create root filesystem squash image

mkdir -p rootfs/share/system

# Flash is capable of at least 5136384 bytes from 2.3.27, 2.3.32, 2.3.33
mksquashfs rootfs filesystem.bin -noI -no-fragments -b 1048576

add_file $FW.bin filesystem



# Add kernel image
md5sum uImage.bin > uImage.md5sum
tar -uf $FW.bin uImage.bin uImage.md5sum
rm uImage.md5sum


