#!/bin/sh
. /usr/libexec/modules/modules.conf
DATE_CONF=/etc/sysconfig/config/date.conf
NTP_CONF=`/bin/cat /etc/sysconfig/config/ntp.conf`
NTP_SERVER=`/bin/cat /etc/sysconfig/config/ntp_server`
GMT_CONF=/etc/sysconfig/config/gmt.conf
DST_CONF=/etc/sysconfig/config/dst.conf
NTP_ACTION_CONF=/etc/sysconfig/config/ntp.action
GMT=`cat $GMT_CONF`
tmpfile=/tmp/tmp.$$

mysettime(){
yy=$1
mm=$2
dd=$3
HH=$4
MM=$5
}

mathweek(){
month=$1
sun=$2

tmp=0
for i in 01 02 03 04 05 06 07 08 09 10 11 12 13 14; do
 week=`date '+%A' -d "$yy$month$i $HH$MM"`
 [ "$week" == "Sunday" ] && {
  tmp=`expr $tmp + 1`
  [ $tmp -eq $sun ] && {
   return `date '+%d' -d "$yy$month$i $HH$MM"`
   break
   }
  }
done
}

/bin/test -f ${NTP_ACTION_CONF} ||\
 echo "auto" > ${NTP_ACTION_CONF}

NTP_ACTION=`cat ${NTP_ACTION_CONF}`
[ "${NTP_ACTION}" == "auto" ] || exit 0

/bin/ntpdate ${NTP_CONF}
[ $? -eq 0 ] || {
 for ser in ${NTP_SERVER}; do
  echo "${ser}" > /etc/sysconfig/config/ntp.conf
  break
 done

 return 1
 }

. ${DST_CONF}
[ "$DST_STATUS" == "Disable" ] && exit

echo `date '+%Y %m %d %H %M'` > $tmpfile

echo "$GMT"|grep -q "-"
[ $? -eq 0 ] || GMT="+${GMT}"
/bin/date `/bin/date -d "${GMT} Hour" +"%m%d%H%M%Y"` >/dev/null 2>&1

mydate=`date '+%Y %m %d %H %M'`
mysettime $mydate

START_DST_DATE=`mathweek 03 2`
END_DST_DATE=`mathweek 11 1`

service_ntp_start $tmpfile
/bin/rm -rf $tmpfile

/bin/test -f ${DST_CONF} && {
 OLD_START_DST_DATE=`/bin/awk -F= /START/'{print $2}' ${DST_CONF}`
 OLD_END_DST_DATE=`/bin/awk -F= /END/'{print $2}' ${DST_CONF}`
 [ x$OLD_START_DST_DATE != x$START_DST_DATE ] && \
  /bin/replaceFile "${DST_CONF}" "START=$OLD_START_DST_DATE" "START=$START_DST_DATE"
 [ x$OLD_END_DST_DATE != x$OLD_END_DST_DATE ] && \
  /bin/replaceFile "${DST_CONF}" "END=$OLD_END_DST_DATE" "END=$OLD_END_DST_DATE"
 } || {
 echo "DST_STATUS=$DST_STATUS" > ${DST_CONF}
 echo "START=$START_DST_DATE" >> ${DST_CONF}
 echo "END=$END_DST_DATE" >> ${DST_CONF}
 }

 [ $mm -gt 3 ] && {
  [ $mm -lt 11 ] && {
   GMT=`expr $GMT + 1`
   echo "$GMT"|grep -q "-"
   [ $? -eq 0 ] || GMT="+${GMT}"
   /bin/date `/bin/date -d "${GMT} Hour" +"%m%d%H%M%Y"` >/dev/null 2>&1
   } || {
   [ $mm -eq 11 ] && {
    [ $dd -le $END_DST_DATE -a $HH -le 2 ] && {
     GMT=`expr $GMT + 1`
     echo "$GMT"|grep -q "-"
     [ $? -eq 0 ] || GMT="+${GMT}"
     /bin/date `/bin/date -d "${GMT} Hour" +"%m%d%H%M%Y"` >/dev/null 2>&1
     }
    }
   }
  } || {
  [ $mm -eq 3 ] && {
   [ $dd -ge $START_DST_DATE -a $HH -ge 2 ] && {
    GMT=`expr $GMT + 1`
    echo "$GMT"|grep -q "-"
    [ $? -eq 0 ] || GMT="+${GMT}"
    /bin/date `/bin/date -d "${GMT} Hour" +"%m%d%H%M%Y"` >/dev/null 2>&1
    }
   }
  }

echo `date '+%Y %m %d %H %M'` > $DATE_CONF
