#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH

. /usr/libexec/modules/modules.conf

/usr/bin/mdadm -D /dev/md1|/bin/grep -q "spare rebuilding"
[ $? -eq 0 ] && {
 return
 } || {
 echo "hdd1 blue clear" > /proc/mp_leds
 echo "hdd2 blue clear" > /proc/mp_leds
 echo "hdd1 red clear" > /proc/mp_leds
 echo "hdd2 red clear" > /proc/mp_leds
 echo "hdd1 blue set" > /proc/mp_leds
 echo "hdd2 blue set" > /proc/mp_leds

 service_rebuild_stop
}
